# Generated by Django 4.0 on 2022-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_calendar', '0002_slot_usertrackinfo_project_creator_project_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrackinfo',
            name='pass_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
