# Generated by Django 4.0 on 2022-05-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_calendar', '0004_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrackinfo',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usertrackinfo',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
