# Generated by Django 4.0 on 2022-05-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_calendar', '0005_alter_usertrackinfo_email_alter_usertrackinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_posted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user_posting_info',
            field=models.ManyToManyField(related_name='project', to='master_calendar.PostingInfo'),
        ),
    ]
